In [3]:
import pandas as pd
import numpy as np

# Data acak
np.random.seed(42)  # agar hasil bisa direproduksi

merek = np.random.choice(['abdul', 'adompo', 'rizal'], size=10)
ukuran = np.random.choice(['S', 'M', 'XL'], size=10)
harga = np.random.randint(500_000, 1_000_001, size=10)

# Buat DataFrame
df = pd.DataFrame({
    'nama_barang': merek,
    'ukuran': ukuran,
    'harga': harga
})

# Tampilkan
print(df)


  nama_barang ukuran   harga
0       rizal     XL  767455
1       abdul     XL  603355
2       rizal      S  735796
3       rizal     XL  714176
4       abdul      M  684779
5       abdul      S  847449
6       rizal      M  921909
7      adompo      M  965148
8       rizal      M  758795
9       rizal      M  986232


In [4]:
#mapping kategori
ukuran_mapping = {
    'S': 1,
    'M': 2,
    'XL': 3
}



In [5]:
df['ukuran'] = df['ukuran'].map(ukuran_mapping)
print(df)

  nama_barang  ukuran   harga
0       rizal       3  767455
1       abdul       3  603355
2       rizal       1  735796
3       rizal       3  714176
4       abdul       2  684779
5       abdul       1  847449
6       rizal       2  921909
7      adompo       2  965148
8       rizal       2  758795
9       rizal       2  986232


In [6]:
#contoh encode labels
import numpy as np


In [7]:
import pandas as pd
import numpy as np

# Data acak
np.random.seed(42)  # agar hasil bisa direproduksi

merek = np.random.choice(['abdul', 'adompo', 'rizal'], size=10)
ukuran = np.random.choice(['S', 'M', 'XL'], size=10)
harga = np.random.randint(500_000, 1_000_001, size=10)
classlabel = np.random.choice(['class1', 'class2'], size=10)

# Buat DataFrame
df = pd.DataFrame({
    'nama_barang': merek,
    'ukuran': ukuran,
    'harga': harga,
    'classlabel': classlabel
})

# Tampilkan
print(df)


  nama_barang ukuran   harga classlabel
0       rizal     XL  767455     class1
1       abdul     XL  603355     class1
2       rizal      S  735796     class1
3       rizal     XL  714176     class1
4       abdul      M  684779     class2
5       abdul      S  847449     class2
6       rizal      M  921909     class2
7      adompo      M  965148     class2
8       rizal      M  758795     class2
9       rizal      M  986232     class1


In [8]:
# mengecek nilai uniq dari classlabel
class_mapping = {label : idx for idx, label in enumerate(np.unique(df['classlabel']))}
print(class_mapping)

{'class1': 0, 'class2': 1}


In [9]:
df['classlabel'] = df['classlabel'].map(class_mapping)
print(df)

  nama_barang ukuran   harga  classlabel
0       rizal     XL  767455           0
1       abdul     XL  603355           0
2       rizal      S  735796           0
3       rizal     XL  714176           0
4       abdul      M  684779           1
5       abdul      S  847449           1
6       rizal      M  921909           1
7      adompo      M  965148           1
8       rizal      M  758795           1
9       rizal      M  986232           0


In [10]:
# Mapping
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}
ukuran_mapping = {'S': 1, 'M': 2, 'XL': 3}

# Terapkan mapping ke dua kolom
df[['classlabel', 'ukuran']] = df[['classlabel', 'ukuran']].apply(
    lambda col: col.map(class_mapping) if col.name == 'classlabel' else col.map(ukuran_mapping)
)

print(df)


  nama_barang  ukuran   harga  classlabel
0       rizal       3  767455           0
1       abdul       3  603355           0
2       rizal       1  735796           0
3       rizal       3  714176           0
4       abdul       2  684779           1
5       abdul       1  847449           1
6       rizal       2  921909           1
7      adompo       2  965148           1
8       rizal       2  758795           1
9       rizal       2  986232           0


In [ ]:
#one-shot encoding

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder



In [15]:
# buat variable penampung sementara
X = df[['nama_barang', 'ukuran', 'harga','classlabel']].values
tabel_transform = ColumnTransformer([
    ('onehot', OneHotEncoder(), [0]),
    ('nothing','passthrough', [1,2,3])])

df_hasil = tabel_transform.fit_transform(X)
print(df_hasil)

[[0.0 0.0 1.0 3 767455 0]
 [1.0 0.0 0.0 3 603355 0]
 [0.0 0.0 1.0 1 735796 0]
 [0.0 0.0 1.0 3 714176 0]
 [1.0 0.0 0.0 2 684779 1]
 [1.0 0.0 0.0 1 847449 1]
 [0.0 0.0 1.0 2 921909 1]
 [0.0 1.0 0.0 2 965148 1]
 [0.0 0.0 1.0 2 758795 1]
 [0.0 0.0 1.0 2 986232 0]]


In [18]:
import pandas as pd

# Misal hasil one-hot menghasilkan 3 kolom: kol_abdul, kol_rizal, kol_adompo
kolom = ['kol_abdul', 'kol_rizal', 'kol_adompo', 'ukuran', 'harga', 'classlabel']

# Konversi ke DataFrame
df_hasil_df = pd.DataFrame(df_hasil.toarray() if hasattr(df_hasil, 'toarray') else df_hasil, columns=kolom)

# Tampilkan
print(df_hasil_df)


  kol_abdul kol_rizal kol_adompo ukuran   harga classlabel
0       0.0       0.0        1.0      3  767455          0
1       1.0       0.0        0.0      3  603355          0
2       0.0       0.0        1.0      1  735796          0
3       0.0       0.0        1.0      3  714176          0
4       1.0       0.0        0.0      2  684779          1
5       1.0       0.0        0.0      1  847449          1
6       0.0       0.0        1.0      2  921909          1
7       0.0       1.0        0.0      2  965148          1
8       0.0       0.0        1.0      2  758795          1
9       0.0       0.0        1.0      2  986232          0


In [19]:
# contoh menggunakan library getDummies

In [22]:
import pandas as pd
import numpy as np

# Seed agar hasil acak bisa direproduksi
np.random.seed(42)

# Buat DataFrame
df = pd.DataFrame({
    'nama_barang': np.random.choice(['abdul', 'rizal', 'adompo'], size=10),
    'ukuran': np.random.choice(['S', 'M', 'XL'], size=10),
    'harga': np.random.randint(500_000, 1_000_001, size=10),
    'classlabel': np.random.choice(['class1', 'class2'], size=10)
})

# Mapping classlabel ke angka
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}
df['classlabel'] = df['classlabel'].map(class_mapping)

# One-hot encoding kolom kategorikal, hasil dalam bentuk 0 dan 1
df_encoded = pd.get_dummies(df, columns=['nama_barang', 'ukuran'], dtype=int)

# Tampilkan hasil
print(df_encoded)


    harga  classlabel  nama_barang_abdul  nama_barang_adompo  \
0  767455           0                  0                   1   
1  603355           0                  1                   0   
2  735796           0                  0                   1   
3  714176           0                  0                   1   
4  684779           1                  1                   0   
5  847449           1                  1                   0   
6  921909           1                  0                   1   
7  965148           1                  0                   0   
8  758795           1                  0                   1   
9  986232           0                  0                   1   

   nama_barang_rizal  ukuran_M  ukuran_S  ukuran_XL  
0                  0         0         0          1  
1                  0         0         0          1  
2                  0         0         1          0  
3                  0         0         0          1  
4                  0     